service: mailgunretry
provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-east-1
  memorySize: 3008
functions:
  app:
    handler: index.handler
    memorySize: 3008
    events:
      - http:
          path: /api/webhook
          method: ANY
          cors: true
    environment:
      MAILGUN_API_KEY: dc60272b1c66aaea69d413d5dcd7b011-ee13fadb-16c1ea7d
      MAILGUN_DOMAIN: sandbox3df0c92ea08b4c88b3b0923bc003cde5.mailgun.org
      TABLE_NAME: mailgun
      DEFAULT_TEST_EMAIL: bellohargbola13@gmail.com
      AWS_SNS_TOPIC_ARN: arn:aws:sns:us-east-1:187584259401:mailgun
